import type { Metadata } from "next";
import { Geist, Geist_Mono, Epilogue, Manrope } from "next/font/google";

import './globals.css'
import { cn } from "@/lib/utils";

import { Toaster } from "@/components/ui/sonner";
import { HeaderNew } from "@/components/globals/header-new";
import { Footer } from "@/components/globals/footer";
import { Plus } from "lucide-react";
import { getUser } from "@/lib/auth-server";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const epilogue = Epilogue({
  subsets: ['latin'],
  variable: '--font-headline',
})

const manrope = Manrope({
  subsets: ['latin'],
  variable: '--font-body',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const currentUser = await getUser()
  return (
    <html lang="en">
      <body

        className={cn(epilogue.variable, manrope.variable, "antialiased", "h-full bg-surface text-on-surface font-body selection:bg-primary-container selection:text-on-primary-container")}
      >
        <HeaderNew />
        <Toaster richColors />
        <main className="pt-12">

          {children}
        </main>
        <Footer />
        {/* Floating Action Button */}
        {currentUser && <Link href={"/admin/recipes/new"} className="cursor-pointer fixed bottom-8 right-8 w-16 h-16 rounded-full braise-gradient text-white shadow-editorial flex items-center justify-center hover:scale-110 active:scale-95 transition-all z-40">
          <Plus size={32} />
        </Link>}

      </body>
    </html>
  );
}
