import type { Metadata } from "next";
import { Geist, Geist_Mono, Epilogue, Manrope } from "next/font/google";

import "./globals.css"
import { cn } from "@/lib/utils";
import { Header } from "@/components/globals/header";
import { Toaster } from "@/components/ui/sonner";
import { HeaderNew } from "@/components/globals/header-new";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const epilogue = Epilogue({
  subsets: ['latin'],
  variable: '--font-headline',
})

const manrope = Manrope({
  subsets: ['latin'],
  variable: '--font-body',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body

        className={cn(epilogue.variable, manrope.variable, "antialiased", "h-full bg-surface text-on-surface font-body selection:bg-primary-container selection:text-on-primary-container")}
      >
        <HeaderNew />
        <Toaster richColors />
        <main className="max-w-7xl mx-auto px-6 pt-16">

          {children}
        </main>
      </body>
    </html>
  );
}
