import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css"
import { cn } from "@/lib/utils";
import { Header } from "@/components/globals/header";
import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(geistSans.variable, geistMono.variable, "antialiased", "h-full ")}
      >
        <Header />
        <Toaster richColors />
        <main className="flex min-h-screen w-full  flex-col items-center justify-between px-7 dark:bg-black sm:items-start">

          {children}
        </main>
      </body>
    </html>
  );
}
